---
clusterName: home-cluster

talosVersion: v1.2.3
kubernetesVersion: v1.24.3
endpoint: "https://k8s.${domainName}:6443"

clusterPodNets:
  - 10.244.0.0/16
  - fd12:3456:789a:244::/96
clusterSvcNets:
  - 10.96.0.0/12
  - fd12:3456:789a:96::/112

cniConfig:
  name: none

nodes:
  - hostname: hydra
    ipAddress: 192.168.2.20
    controlPlane: true
    installDisk: /dev/sda
    nameservers:
      - 1.1.1.1
      - 9.9.9.9
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.2.20/24
          - ${ipv6Hydra}
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.2.254
          - network: ::/0
            gateway: ${ipv6Gateway}
        mtu: 1500

controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        apiServer:
          admissionControl: []
          certSANs:
            - ${clusterEndpointIP}
            - k8s.${domainName}
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        controllerManager:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
            node-cidr-mask-size-ipv4: "24"
            node-cidr-mask-size-ipv6: "112"
        discovery:
          registries:
            service:
              disabled: true
        extraManifests:
          - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/v0.6.0/deploy/standalone-install.yaml
        proxy:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        scheduler:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      machine:
        certSANs:
          - ${clusterEndpointIP}
          - k8s.${domainName}
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
            rotate-server-certificates: "true"
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - k8s.${domainName}
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"

worker:
  patches:
    - |-
      cluster:
        discovery:
          registries:
            service:
              disabled: true
      machine:
        certSANs:
          - ${clusterEndpointIP}
          - k8s.${domainName}
        extraManifests:
          - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
        kubelet:
          extraArgs:
            rotate-server-certificates: "true"
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - k8s.${domainName}
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
