---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - data-pvc.yaml
  - main-pvc.yaml
  - helm-release.yaml
patchesStrategicMerge:
  - patches/postgres.yaml
