# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
    namespace: default
type: Opaque
stringData:
    USERNAME: ENC[AES256_GCM,data:T5IGHVE=,iv:qegffn5DXuEERk1LZyHshJlGuNBXMMfiUItay8ZJWBk=,tag:zfo96Y/XJ3oFGclOns2/Fw==,type:str]
    PASSWORD: ENC[AES256_GCM,data:GBMCUiogtdPKD9qZRzEaRBbu2D5ZCpVXHxlczGexh7fCxcPSb1RQsAq73g==,iv:FaBIK61zPOhBJeY1U14MczllGEAvADBDweFTeW2NfCc=,tag:Ve27Tmg8p07btT2XgjWVuA==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:vtjLp/Sy8ShuDxqwqas0vfSeXooJdTU=,iv:L/heIq7I4DfhWO3MO9yrnooN3FmeCNn2Tzh3utqUKFk=,tag:Txpdcc+6R0Kdef23121zTQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:4QwPpaBJdITpE92u1+fASUmx7Q==,iv:3jD1e53RFooZcwwoqAXDXgWAe5le0ktQIXliugMd+VA=,tag:56hHkfGwrnP5RVY/MZjZ7w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:CVslcxA79aw5,iv:PMsAjr2md6STmtvvHUxfCMlSIBTB7M2UIq1PZeX6uck=,tag:M8GHGjmWuKulmopPmQcdrQ==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:161Wcuv5gW34gfnqh1omv3+iimCTjuPGprkW+SpwWBHQIn0RbqEkU2AlK/w=,iv:Y0AFd4kZxphboCaWGraZMeLnh5zKlys8EwZmvHjzvKA=,tag:duvdF7iHz1Zm8MkHLmNZvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM1NuYW1pQ3NSOXREWk9S
            b0p5NHc4L2MyYSszaCtSS29ibU1LclRDZzB3CkYrbHBUQnl4NE5mR05PcFJrM3pl
            MzljWDREci9lVmVWVlA3ZSthbHlTcmMKLS0tIG9WVk1vL2VnUHlmaG1yeXhabXZI
            MldTQ01rSXBUbEx1KzEyaDdMd1NBNW8K8Joob5CYTZ8rrwTL3xnY3LUsI82pZCq6
            KKNC3/TrmMyu+7JffQW8akZjy8+Qu3SfuH85f76O8JYxnXRZOjI4Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-01T11:46:44Z"
    mac: ENC[AES256_GCM,data:Il+nvYd0CVla61AVWkGXdYRnz2+f66IFoO8vL0FlfpgzIm/bzsW6KtBMWkd8VaEdu5im+wTkdN79t1rJskHaQpOjYPIm+qLIEoD+v6tTZXFKyil9xUs8sv8PVs1VoMCWDCvW9hm/floQmgTf09/eXpaYAApKH35lABMAu/O4Y0Q=,iv:SUmTesh5x9IrWC4H0nIa5q/ElsI0bCVIEamh/dI0a4Y=,tag:XAUBorEttoW00uA7SRYAtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
