---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghost
      tag: 5.14.2
      pullPolicy: IfNotPresent

    persistence:
      content:
        enabled: true
        storageClass: "ceph-block"
        accessMode: ReadWriteOnce
        size: 1Gi

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "dyn.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "ghost"
          hajimari.io/appName: "Ghost"
        hosts:
          - host: "blog.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
            hosts:
              - "blog.${SECRET_DOMAIN}"
