---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-main
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: "ceph-block"
