# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-postgres-secret
    namespace: default
type: Opaque
stringData:
    superUserPassword: ENC[AES256_GCM,data:ZusXfMQk1rEPeU81MNS59fA9W6cs71vo/5ivRR3qjcVR/1hKUY7C1Y+RO58=,iv:wL/lyF9C+XtoKi0FcDqNa93qtlpJAeoAMudFXDsDNy8=,tag:bMO5AkZYWa165D9kgdkQig==,type:str]
    replicationUserPassword: ENC[AES256_GCM,data:JwiG683PIH5YfgGo0+s2/1s4WLnsFIGYJPx5iuIX9+zoVNe1mReH5LCjM6o=,iv:NzCGIPGALf6bzkfh9cX3y0pzM9Zl/Lks+gXMLU5iYng=,tag:aUh3wQ/zi7j0nLjUqAFQTg==,type:str]
    myDbPassword: ENC[AES256_GCM,data:xfC775fvBnMvVRO+ZpXIcKyjVAzDCa7oxe2d3RiHbNuI553GsZw5FFjBxyE=,iv:Fi0s+68Wr8hYTQuobVW/OPvrOlnjdXzZFkd4+2ckat4=,tag:F/l4liy9xhzzGnQVh+74bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT3orZ0NWaElaRElYSVZp
            QnVGOGx5Vk9SdFNZK2ljb01KK1V0dC9qODFNClhlVzhPSDdqbVZpeUNROE9tR2tp
            MnZsUmVrSEhpUmZNVkVsS0tPenJJaFEKLS0tIDBYb0dvbno0V1BoN3J6RFQvSnlW
            d2owWVh1bnlFL3J4ODRzNnZKak4vTmcKSw7eVG1iRVC2vw82SewUwtoGDhQJLJVL
            vA91/IQ3jCrYZQdbotWSKW1XCafoDv4T4/1SvXeWEmD5H9/7egN9lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-26T11:48:15Z"
    mac: ENC[AES256_GCM,data:/g5xbmJoZV1ydJ4tHGzxzHAJ1brmJ80i0Nx+wPQNRhPCwwmhTaPncvduONm5xxIdAJmYusk6O28CPa2D+VGHgFMBTTZv+OgPvZcLnC3eUo6+fq5PhCAGsD2PGBo6jjrEM2tk93VKhXjk56DWTA4L8/bFv6OZRd4TEpW/mtkxLkw=,iv:rLIfh199ovh9toLfqLQiH6Z7QK4Kx+hfFrYa0IKQPb8=,tag:IDfZYWgkVdpYI0t3KY/6lA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
