---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2022.8.2
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2022.8.2

    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        external-dns.alpha.kubernetes.io/target: "dyn.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
      hosts:
        - host: auth.${SECRET_DOMAIN}
          paths:
            - path: /

      tls:
        - secretName: "${SECRET_DOMAIN/./-}-tls"
          hosts:
            - auth.${SECRET_DOMAIN}

    geoip:
      enabled: false
    authentik:
      email:
        host: ${SECRET_SMTP_HOST}
        port: 587
        username: ${SECRET_SMTP_USERNAME}
        password: ${SECRET_SMTP_PASSWORD}
        use_tls: true
        from: ${SECRET_SMTP_FROM}
      secret_key: ${SECRET_AUTHENTIK_SECRET_KEY}
      log_level: debug

      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s

      postgresql:
        host: "authentik-postgres"
        name: "authentik"
        user: "authentik"
        password: ${SECRET_AUTHENTIK_POSTGRES_PASSWORD}
      redis:
        host: "{{ .Release.Name }}-redis-master"
        password: ${SECRET_AUTHENTIK_REDIS_PASSWORD}

    redis:
      enabled: true
      auth:
        enabled: true
        password: ${SECRET_AUTHENTIK_REDIS_PASSWORD}
