---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 5m0s
  url: ssh://git@github.com/Iudicael/home-ops
  ref:
    branch: main
  secretRef:
    name: github-deploy-key
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-cluster
