# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-postgres-secret
  namespace: security
type: Opaque
stringData:
  superUserPassword: ENC[AES256_GCM,data:h/hZSZpKf/pSSuPRC61+j/aQd/34Z3sg7tK/6mdaYRLFzGyv3Mlj3M/4XPI=,iv:95Yosgj+AGTuCGGeh6Oq3kmfOeSp1UxcjNcWh2ziTuw=,tag:MEjYtlVRXLFI5mj1QFuy0g==,type:str]
  replicationUserPassword: ENC[AES256_GCM,data:PPzgvgWeQHoZluBvpqFWXBNhuepT6/WOtlLV14PXfUJd+f/dp4u0V0GVBKs=,iv:3aZ/zjpK/2nd3UYleYOovi6XeWSU821KXW+DnL4pRDE=,tag:3jvoRWRh2MfCY8fmUXmDpQ==,type:str]
  myDbPassword: ENC[AES256_GCM,data:T4PgUQvhXHNsH9bG8ZotCgyYK38uG6YoL+UOgmHwWcPK3SipEA1id9lJW/U=,iv:OyyE1Oy/I2IHDKaNw4CHxkB5PDYy6QMX3NtZiaqK97U=,tag:/XhloADTv0765f7m0B7zwQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT3orZ0NWaElaRElYSVZp
        QnVGOGx5Vk9SdFNZK2ljb01KK1V0dC9qODFNClhlVzhPSDdqbVZpeUNROE9tR2tp
        MnZsUmVrSEhpUmZNVkVsS0tPenJJaFEKLS0tIDBYb0dvbno0V1BoN3J6RFQvSnlW
        d2owWVh1bnlFL3J4ODRzNnZKak4vTmcKSw7eVG1iRVC2vw82SewUwtoGDhQJLJVL
        vA91/IQ3jCrYZQdbotWSKW1XCafoDv4T4/1SvXeWEmD5H9/7egN9lg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2021-11-10T22:45:16Z"
  mac: ENC[AES256_GCM,data:/zXDe8K6WXkfo1AUWZCSlX6RsDidNufhIvlcko8iquTBFrI5z/cwWh/gXBlKHEygbSBwx/Ky/MUwbLJ+DQR2SBCVI1kyUHOlCZ/f9nqOgRbgH3TWLDNQSFj+KngoDGYZ72UnYA+cn40BLfgdTqLjgvT1wCTPZrhHjAa7vZ4tfIA=,iv:hQBtVy6J8vNVAEByF4p6WG3H+sTqTePjWw5hplnUo/o=,tag:GwTUlNtk4jqTq0K9jjtZ3g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
