---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tigera-operator
  namespace: tigera-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: tigera-operator
      version: v3.24.1
      sourceRef:
        kind: HelmRepository
        name: project-calico-charts
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    installation:
      enabled: true
      registry: quay.io
      imagePath: calico
      calicoNetwork:
        # Note: The ipPools section cannot be modified post-install.
        ipPools:
          - blockSize: 26
            cidr: "10.244.0.0/16"
            encapsulation: "None"
            natOutgoing: Enabled
            nodeSelector: all()
          - blockSize: 120
            cidr: "fd12:3456:789a:244::/56"
            encapsulation: "None"
            natOutgoing: Enabled
            nodeSelector: all()
      nodeMetricsPort: 9091
      typhaMetricsPort: 9093
