---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ghost
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghost
      tag: 5.5.0
      pullPolicy: IfNotPresent

    env:
      url: "https://blog.${SECRET_DOMAIN}"
      database__client: mysql
      database__connection__host: ghost-cluster-mysql-master.default.svc.home-cluster.local
      database__connection__user: ghost
      database__connection__password: ${SECRET_GHOST_MYSQL_PASSWORD}
      database__connection__database: ghost
      NODE_ENV: production

    persistence:
      content:
        enabled: true
        storageClass: "ceph-block"
        accessMode: ReadWriteOnce
        size: 1Gi

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "dyn.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "ghost"
          hajimari.io/appName: "Ghost"
        hosts:
          - host: "blog.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
            hosts:
              - "blog.${SECRET_DOMAIN}"
