---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grocy
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: mysql-operator
      namespace: default
  values:
    image:
      repository: linuxserver/grocy
      tag: version-v3.1.2
      pullPolicy: IfNotPresent

    env:
      TZ: "${TIMEZONE}"
      GROCY_CULTURE: "nl"
      GROCY_CURRENCY: "EUR"

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "dyn.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cart-variant"
          hajimari.io/appName: "Grocy"
        hosts:
          - host: "grocy.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
            hosts:
              - "grocy.${SECRET_DOMAIN}"

    persistence:
      config:
        enabled: true
        storageClass: "ceph-block"
        accessMode: ReadWriteOnce
        size: 5Gi
