# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: security
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:z2i4ypn4gmOwGlp49u0RS/VMNyim7qaCNsVfEi1JrdJhXe7kNYk=,iv:Xy2rEBBgHKeBn2cgwOfTqHTIrsUhD/OafUxfWKNNBrU=,tag:CyRQzQu9etbCpzGfAyaRLg==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:z6kgvXEI2zX563KScgpBRPr2k4w=,iv:Dk8C++rnUuVVCJQupeH2K9oGFdItmc8L5Kv/D9E5QRI=,tag:rwRmCQyljyfjAenURzosgQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:66E24FKdSCsbTNGusDUoIlmWhpAlEaQ=,iv:A0cG+o8fskgY1J2uSNL7u0QTAqPRPVKARBS6kXvrKnA=,tag:w2SKFzcX7ibzNMVpyooQEw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:uHmJHTiz9WFutbSKh/6Xo4RIQw==,iv:ZZwzoAPdYk/TYRZPonIwNiEzqTk6iFzhqwvlR+Z+syw=,tag:zfbsDtBEit9P3RvhNrqhWA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:MuetxhOkIanK7dkHQWFXRSgxOva40DLUQCtkIMHr0oZ0ncwD1cNtILBeFZXuaTfhJOOn4awm1hTUY1TzTW80N8JGdODYnXvoxCkOulhew2AkB23iPrl2eW4rKzqxmRe4gTGwQCJvME+ryxFlLkPFLLl6FQqsANM=,iv:YshdNjxS3JQARtv+8JtMQ7kllG1diTwattv7vkj0Wtk=,tag:+xxZkDVsgd6XH3/+W4CAiA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:+zgOrSN/ApdW1eA=,iv:7+8ywS0hVA8G0wNSr2GvAC0k/D10ytYSJtx18ARyx4g=,tag:SwyXNRxRlNFFZ9tvjfALZA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:bd3rRxlxMNWHUhC9FF2iJ4GZ74u1u2D3Y+JKAsU5fb8jofb4jOhuFL57bjk=,iv:matIQ+YE8SsyxMLz2vbo2f2Q7qPWQ/Ra4LyDqaHyh98=,tag:UnGDvG73eRXILRCFq7ZnrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dVYzWkVESVhycUJUTi9u
            UmExOVdhRkRXL1RldWJMSERjbFJ4OXBDMHhNCk5LNGZ1RjFxUXJPb281Vy9RRzJS
            b1BzaVZtMzN3bGRjcXRtcVFqV0ZlenMKLS0tIGdBa2NDbmhieXR4WTB5ZVoyUFkw
            RVAzQ2ZYUVBjWmVDU0liTzRGajRKOTQKpMqGEMymU3NFhXFYzI7YZNKKqqCDPkq1
            Nd7cUXsmMDj6dLXdUxnyOmPrfDc+dzBucNkK097vGKRfPXuuCKF+5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-01T12:04:24Z"
    mac: ENC[AES256_GCM,data:NnhrOH0LUNmiB4wxAdiMHnxcvcaF4zWPmuV8yQheh9SdIHZ5W7e2+IEEpLy8B1UYcLzQIYnMKeQIkxW/PJ2BlrqoHEUqedZvaA4SSOeSWicTTVnvfPzbpQODIoL+c1hMYmaoPfhJYrPOF4IEAFsJqyAZqaHjk5xicgLdZ5ShACY=,iv:DEnMhhUQ4ekDIZ9gaQqjZr00p9Wwy+vcHMUiO9venc4=,tag:+tvDT8K/N4BumoCg2ZHIlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
