---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: hkotel/mealie
      tag: frontend-v1.0.0beta-3
      pullPolicy: IfNotPresent

    env:
      TZ: "${TIMEZONE}"

    service:
      main:
        ports:
          http:
            port: 3000
          api:
            enabled: true
            port: 9000

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "dyn.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "food"
          hajimari.io/appName: "Mealie"
        hosts:
          - host: "meals.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
            hosts:
              - "meals.${SECRET_DOMAIN}"

    persistence:
      api-data:
        enabled: true
        mountPath: /app/data/
        storageClass: "ceph-block"
        accessMode: ReadWriteOnce
        size: 10Gi

    api:
      image:
        repository: hkotel/mealie
        tag: api-v1.0.0beta-2
        pullPolicy: IfNotPresent

      env:
        TZ: "${TIMEZONE}"
        DEFAULT_EMAIL: david@${SECRET_DOMAIN}
        BASE_URL: https://meals.${SECRET_DOMAIN}
        ALLOW_SIGNUP: false

      volumeMounts:
        - name: api-data
          mountPath: /app/data/
