---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: cloudnative-pg
      namespace: default
  values:
    image:
      repository: ghcr.io/miniflux/miniflux
      tag: 2.0.46
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "dyn.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "rss-box"
          hajimari.io/appName: "Miniflux"
        hosts:
          - host: "rss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
            hosts:
              - "rss.${SECRET_DOMAIN}"
