# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: miniflux
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:TjqB+s2XC19wS0+BAF1JE1SYIX8xk95/MA4/2y1ZEdvSKsnNERoE/59JKMRs4bLf0CS/Rtr5BX0yvvvbE2HoNAeUdnHOh2fugK8OMB+cWIsV8hrOfXnsIEJy5ZRoVhmCpgzVhRKKsVLhd2UpIRUzWRCxNWGhdBdBW2w42qocsL8=,iv:bRKxl3GjqWEEfjp5W2tCymK0m+ngm4qlL/BlfU8Phkk=,tag:piuDNOIAnVeMmfxRk0BkvQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:tZrcjlpS5Wk=,iv:0A05aQGXHTK0LFpbvnYjTBkBge5aGLwGNYeerQMiDSw=,tag:ynTnzJlJyQex3DkfeoXaKQ==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:KW9ioypS1+FH7BeSzEh9d/BcvOKfAk3cfWnCq5b6ocQIenWOI9UyONE+7IA=,iv:bGOH7HUfF2lBMZL0T5eeKTyIF9R6Cz+XQQJjtR4FNVM=,tag:8A/MrLzgQpZXVssXsusYjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZb2RmUWVzRytJWmJWNzJP
            RlJyWHJESE5EbEZuTVpRUVBlR0o2TkJ0M2hRCmE5WlBmTHd1OGdnTkNUN0Nla0JU
            R0grWFc4VTBRQm5FeVFWUHZ0Y09aR1UKLS0tIExGVWIxQlhZejNJVmg3UlZRL3Q3
            dVBIcFdmUU93L0F3bmViL21wVDViOGsKKjGomqMPdCOd4iZzvX5qOnSDSfYhEcc8
            vpagH0j3T34Ux/ICQu7UBrnMckceRFrqVNXhhtvbROh1QaapEMXrfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-01T16:19:39Z"
    mac: ENC[AES256_GCM,data:QJzmzGTOwic6xRizlsJckbqAiXbnw+rA1x0wFT0Os+vUeGVLPk5sZZlD/BwRYKWjqLMKfnPMMZTrya++egXaOSNhUFy71NYtNYDYY8FApy40NYWVFB3ZWAG3WZSEOOoBrl6swLk7dufblnNOPX3YUWoWEL7ewoxfvP8D+gWMN+U=,iv:k51L0jsr7MGDF9gmvd4pl4/q9q4x0cj8fn7CVk0pYOo=,tag:rDjYD4TuGA+Hk2ZQPAo/Cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
